### ISSUE TITLE
Resolving Queries on .NET Core 3.0 fails

### ISSUE THREAD

**Issue by JakubK** [lukemurray/EntityGraphQL#22]
I wanted to use this Library in my project, but couldn't test it in my project. So I've downloaded the sample one and done some investigation.
I found out that running the app on .NET Core 3.0 and trying to resolve some query is throwing the following logs:
``System.NotSupportedException: The collection type 'EntityGraphQL.QueryVariables' on 'EntityGraphQL.QueryRequest.Variables' is not supported.
   at System.Text.Json.Serialization.JsonClassInfo.GetElementType(Type propertyType, Type parentType, MemberInfo memberInfo)
   at System.Text.Json.Serialization.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.Serialization.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)``

**Comment by lukemurray** [comment]
Thanks. I've not tried on dotnet 3.0 which I believe is still in pre release?

It looks like the new Jason serialiser is having trouble with the dictionary type. I'll try to play with dotnet 3.0 soon


________________________________

**Comment by JakubK** [comment]
@lukemurray  I also wanted to add something new what I found out a few minutes ago. Updating to .NET Core 3.0 is also causing some issues with relationship between DbContext and your Code. Every queries are being resolved to proper SQL statements, but it returns empty data sets in json.

**Comment by lukemurray** [comment]
@JakubK I installed dotnet 3.0 and changed the demo project to 3.0 and I can make queries etc fine. Any change you can replicate this using the demo project or another one you can share with me? Thank

**Comment by JakubK** [comment]
Well I've just upgraded the demo to dotnet 3.0 again and it still doesn't work.
However I had to make some other changes than just updating the verion in *.csproj. 
There are also some things to do in the Startup before you can run your app.
I'll attach here the zip with my Project that fails to resolve the Query.
[EntityGraphQLDemo.zip](https://github.com/lukemurray/EntityGraphQL/files/3554523/EntityGraphQLDemo.zip)

**Comment by lukemurray** [comment]
So I'm currently using dotnet 3.x and this library. I no longer get the above errors with the latest release. Let me know if you have any other issues.
