### ISSUE TITLE
Accessing other services via mutations doesn't work

### ISSUE THREAD

**Issue by JakubK** [lukemurray/EntityGraphQL#25]
Hello,
I have encountered an issue while trying to access some service other service from my Mutation,
I'm passing my services as mutation args to the QueryObject method but it doesn't really matter because I'm getting the following StackTrace after execution of `MakeSchema` method:

``Unhandled Exception: System.MissingMethodException: Cannot create an instance of an interface.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at EntityGraphQL.Schema.MutationType..ctor(String methodName, ISchemaType returnType, Object mutationClassInstance, MethodInfo method, String description)
   at EntityGraphQL.Schema.MappedSchemaProvider`1.AddMutationFrom[TType](TType mutationClassInstance)
   at SportLeagueAPI.GraphQL.AppSchema.MakeSchema() in D:\SportLeagueAPI\GraphQL\AppSchema.cs:line 18
   at SportLeagueAPI.Startup.ConfigureServices(IServiceCollection services) in D:\SportLeagueAPI\Startup.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at SportLeagueAPI.Program.Main(String[] args) in D:\SportLeagueAPI\Program.cs:line 10``

**Comment by lukemurray** [comment]
Can you share any more information, like what you are doing at `AppSchema.cs:line 18`?

Looks like it is trying to create an instance of an object that it needs, but the Type is an Interface.

**Comment by lukemurray** [comment]
Closing until I can get more information on this. Also note the new way to inject services with DI `WithService<>()` for query fields and just including the Services in mutations.
