### ISSUE TITLE
Can't get it to work with playground/graphiql/altair

### ISSUE THREAD

**Issue by Peter-Optiway** [lukemurray/EntityGraphQL#35]
Can't get it to work with playground/graphiql/altair all of them complain that `Mutation fields must be an object with field names as keys or a function which returns such an object.`, i have no mutations defined.

Is this a bug in this library or the others?

**Comment by lukemurray** [comment]
Are you using the `.graphql` file output or the introspection queries? Can you reproduce it with the demo project in this repo? I removed the mutations from it and GraphiQL still works fine. So I need a bit more information I think.

**Comment by Peter-Optiway** [comment]
When i visit graphiql it runs the following query
```
  query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }
      subscriptionType { name }
      types {
        ...FullType
      }
      directives {
        name
        description
        locations
        args {
          ...InputValue
        }
      }
    }
  }

  fragment FullType on __Type {
    kind
    name
    description
    fields(includeDeprecated: true) {
      name
      description
      args {
        ...InputValue
      }
      type {
        ...TypeRef
      }
      isDeprecated
      deprecationReason
    }
    inputFields {
      ...InputValue
    }
    interfaces {
      ...TypeRef
    }
    enumValues(includeDeprecated: true) {
      name
      description
      isDeprecated
      deprecationReason
    }
    possibleTypes {
      ...TypeRef
    }
  }

  fragment InputValue on __InputValue {
    name
    description
    type { ...TypeRef }
    defaultValue
  }

  fragment TypeRef on __Type {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                }
              }
            }
          }
        }
      }
    }
  }
```
And gets the following response 
```
{
  "errors": [],
  "data": {
    "__schema": {
      "queryType": {
        "name": "Query"
      },
      "mutationType": {
        "name": "Mutation"
      },
      "subscriptionType": null,
      "types": [
        {
          "kind": "OBJECT",
          "name": "__Directive",
          "description": "Information about directives",
          "fields": [
            {
              "name": "name",
              "description": "",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "description",
              "description": "",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "locations",
              "description": "",
              "args": [],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "SCALAR",
                  "name": "String",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "args",
              "description": "",
              "args": [],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "OBJECT",
                  "name": "__InputValue",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": ""
            }
          ],
          "inputFields": [],
          "interfaces": [],
          "enumValues": [],
          "possibleTypes": []
        },
        {
          "kind": "OBJECT",
          "name": "__EnumValue",
          "description": "Information about enums",
          "fields": [
            {
              "name": "name",
              "description": "",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "description",
              "description": "",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "isDeprecated",
              "description": "",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "Boolean",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "deprecationReason",
              "description": "",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            }
          ],
          "inputFields": [],
          "interfaces": [],
          "enumValues": [],
          "possibleTypes": []
        },
        {
          "kind": "OBJECT",
          "name": "__Field",
          "description": "Information about fields",
          "fields": [
            {
              "name": "name",
              "description": "",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "description",
              "description": "",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "args",
              "description": "",
              "args": [],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "OBJECT",
                  "name": "__InputValue",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "type",
              "description": "",
              "args": [],
              "type": {
                "kind": "OBJECT",
                "name": "__Type",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "isDeprecated",
              "description": "",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "Boolean",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "deprecationReason",
              "description": "",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            }
          ],
          "inputFields": [],
          "interfaces": [],
          "enumValues": [],
          "possibleTypes": []
        },
        {
          "kind": "OBJECT",
          "name": "__InputValue",
          "description": "Arguments provided to Fields or Directives and the input fields of an InputObject are represented as Input Values which describe their type and optionally a default value.",
          "fields": [
            {
              "name": "name",
              "description": "",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "description",
              "description": "",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "type",
              "description": "",
              "args": [],
              "type": {
                "kind": "OBJECT",
                "name": "__Type",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "defaultValue",
              "description": "",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            }
          ],
          "inputFields": [],
          "interfaces": [],
          "enumValues": [],
          "possibleTypes": []
        },
        {
          "kind": "OBJECT",
          "name": "__Schema",
          "description": "A GraphQL Schema defines the capabilities of a GraphQL server. It exposes all available types and directives on the server, as well as the entry points for query, mutation, and subscription operations.",
          "fields": [
            {
              "name": "queryType",
              "description": "",
              "args": [],
              "type": {
                "kind": "OBJECT",
                "name": "__Type",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "mutationType",
              "description": "",
              "args": [],
              "type": {
                "kind": "OBJECT",
                "name": "__Type",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "subscriptionType",
              "description": "",
              "args": [],
              "type": {
                "kind": "OBJECT",
                "name": "SubscriptionType",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "types",
              "description": "",
              "args": [],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "OBJECT",
                  "name": "__Type",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "directives",
              "description": "",
              "args": [],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "OBJECT",
                  "name": "__Directive",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": ""
            }
          ],
          "inputFields": [],
          "interfaces": [],
          "enumValues": [],
          "possibleTypes": []
        },
        {
          "kind": "OBJECT",
          "name": "__Type",
          "description": "Information about types",
          "fields": [
            {
              "name": "kind",
              "description": "",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "name",
              "description": "",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "description",
              "description": "",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "inputFields",
              "description": "",
              "args": [],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "OBJECT",
                  "name": "__InputValue",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "interfaces",
              "description": "",
              "args": [],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "OBJECT",
                  "name": "__Type",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "enumValues",
              "description": "Enum values available on type",
              "args": [
                {
                  "name": "includeDeprecated",
                  "description": null,
                  "type": {
                    "kind": "SCALAR",
                    "name": "Boolean",
                    "ofType": null
                  },
                  "defaultValue": null
                }
              ],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "OBJECT",
                  "name": "__EnumValue",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "possibleTypes",
              "description": "",
              "args": [],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "OBJECT",
                  "name": "__Type",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "ofType",
              "description": "",
              "args": [],
              "type": {
                "kind": "OBJECT",
                "name": "__Type",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "fields",
              "description": "Fields available on type",
              "args": [
                {
                  "name": "includeDeprecated",
                  "description": null,
                  "type": {
                    "kind": "SCALAR",
                    "name": "Boolean",
                    "ofType": null
                  },
                  "defaultValue": null
                }
              ],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "OBJECT",
                  "name": "__Field",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": ""
            }
          ],
          "inputFields": [],
          "interfaces": [],
          "enumValues": [],
          "possibleTypes": []
        },
        {
          "kind": "SCALAR",
          "name": "Boolean",
          "description": null,
          "fields": [],
          "inputFields": [],
          "interfaces": [],
          "enumValues": [],
          "possibleTypes": []
        },
        {
          "kind": "OBJECT",
          "name": "Company",
          "description": "",
          "fields": [
            {
              "name": "name",
              "description": "",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            }
          ],
          "inputFields": [],
          "interfaces": [],
          "enumValues": [],
          "possibleTypes": []
        },
        {
          "kind": "OBJECT",
          "name": "CompanyPagination",
          "description": "Company Pagination",
          "fields": [
            {
              "name": "total",
              "description": "total records to match search",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "Int",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "pageCount",
              "description": "total pages based on page size",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "Int",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            },
            {
              "name": "companies",
              "description": "collection of companies",
              "args": [],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "OBJECT",
                  "name": "Company",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": ""
            }
          ],
          "inputFields": [],
          "interfaces": [],
          "enumValues": [],
          "possibleTypes": []
        },
        {
          "kind": "SCALAR",
          "name": "Float",
          "description": null,
          "fields": [],
          "inputFields": [],
          "interfaces": [],
          "enumValues": [],
          "possibleTypes": []
        },
        {
          "kind": "SCALAR",
          "name": "ID",
          "description": null,
          "fields": [],
          "inputFields": [],
          "interfaces": [],
          "enumValues": [],
          "possibleTypes": []
        },
        {
          "kind": "SCALAR",
          "name": "Int",
          "description": null,
          "fields": [],
          "inputFields": [],
          "interfaces": [],
          "enumValues": [],
          "possibleTypes": []
        },
        {
          "kind": "OBJECT",
          "name": "Mutation",
          "description": "The mutation type, represents all updates we can make to our data",
          "fields": [],
          "inputFields": [],
          "interfaces": [],
          "enumValues": [],
          "possibleTypes": []
        },
        {
          "kind": "OBJECT",
          "name": "Query",
          "description": "The query type, represents all of the entry points into our object graph",
          "fields": [
            {
              "name": "companies",
              "description": "Collection of companies",
              "args": [],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "OBJECT",
                  "name": "Company",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": null
            },
            {
              "name": "companyPager",
              "description": "Pagination. [defaults: page = 1, pagesize = 10]",
              "args": [
                {
                  "name": "page",
                  "description": null,
                  "type": {
                    "kind": "SCALAR",
                    "name": "Int",
                    "ofType": null
                  },
                  "defaultValue": null
                },
                {
                  "name": "pagesize",
                  "description": null,
                  "type": {
                    "kind": "SCALAR",
                    "name": "Int",
                    "ofType": null
                  },
                  "defaultValue": null
                }
              ],
              "type": {
                "kind": "OBJECT",
                "name": "CompanyPagination",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": null
            }
          ],
          "inputFields": [],
          "interfaces": [],
          "enumValues": [],
          "possibleTypes": []
        },
        {
          "kind": "SCALAR",
          "name": "String",
          "description": null,
          "fields": [],
          "inputFields": [],
          "interfaces": [],
          "enumValues": [],
          "possibleTypes": []
        },
        {
          "kind": "OBJECT",
          "name": "SubscriptionType",
          "description": "Information about subscriptions",
          "fields": [
            {
              "name": "name",
              "description": "",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": ""
            }
          ],
          "inputFields": [],
          "interfaces": [],
          "enumValues": [],
          "possibleTypes": []
        }
      ],
      "directives": []
    }
  }
}
```

After that it prints out the following:
Error: Mutation fields must be an object with field names as keys or a function which returns such an object.
    at exports.default (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.min.js:1:585520)
    at defineFieldMap (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.min.js:1:633410)
    at GraphQLObjectType.getFields (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.min.js:1:641830)
    at typeMapReducer (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.min.js:1:676101)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.min.js:1:680178)
    at exports.buildClientSchema (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.min.js:1:709654)
    at https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.min.js:1:47533

**Comment by Peter-Optiway** [comment]
A example can be found https://github.com/Peter-Optiway/GraphQLTest

**Comment by JTravis76** [comment]
Ok, I confirmed this with several of my projects and the example your shared. One must have a least one mutation in order to work. I even tried earlier version of EntityGraphQL and got the same result. Guessing this bug probably existed for a while.

Added the following to your example, removed the error.
```cs
var schema = SchemaBuilder.FromObject<DBContext>();
 schema.AddMutationFrom(new MutationSvc());
services.AddSingleton(schema);
```

```cs
public class MutationSvc {

    [EntityGraphQL.Schema.GraphQLMutation("Add/Update an Company")]
    public Company Company(DBContext context, Company company)
    {
        if (company.Id == 0)
            context.Add(company);
        else
            context.Update(company);

         context.SaveChanges();
         return company;
     }
 }
```

**Comment by lukemurray** [comment]
OK, I run master of this repo and I do not get this. Master uses graphiql 0.16 which isn't even the latest, 0.17.5 is. I have updated to that version and it also works.

I noticed that you seem to be using graphiql/0.11.11. If you upgrade your graphiql version it supports an empty Mutation type (which is what the data returns).

I guess, it might be better that EntityGraphQL doesn't return the empty mutation type at all. But until then, you should be able to just use the latest graphiql
