### ISSUE TITLE
MissingMethodException after trying to add EF migrations to the project

### ISSUE THREAD

**Issue by blackdwarf** [lukemurray/EntityGraphQL#81]
Hi,

I've tried out this nice library and it worked like a charm. I then tried to add migrations to my project, and had to add `Microsoft.EntityFrameworkCore.Design` package to be able to do `dotnet ef` properly for migrations. When I do that, I can get the migration, but as long as the dependency is in the project, when I try to `dotnet run` the web app, I get the following error:

```
Unhandled exception. System.MissingMethodException: Method not found: 'System.String Humanizer.InflectorExtensions.Singularize(System.String, Boolean)'.
   at EntityGraphQL.Schema.SchemaBuilder.AddFieldWithIdArgumentIfExists[TContextType](SchemaProvider`1 schema, Type contextType, Field fieldProp)
   at EntityGraphQL.Schema.SchemaBuilder.FromObject[TContextType](SchemaProvider`1 schema, Boolean autoCreateIdArguments, Boolean autoCreateEnumTypes, Func`2 fieldNamer)
   at EntityGraphQL.Schema.SchemaBuilder.FromObject[TContextType](Boolean autoCreateIdArguments, Boolean autoCreateEnumTypes, Func`2 fieldNamer)
   at aspnetcore.Startup.ConfigureServices(IServiceCollection services) in C:\projects\RecipeBox\servercsharp\Startup.cs:line 38
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at aspnetcore.Program.Main(String[] args) in C:\projects\RecipeBox\servercsharp\Program.cs:line 16
```

This goes away as soon as I remove the `Microsoft.EntityFrameworkCore.Design` package.

Anyone has an idea what is happening? I am thinking this could be because there is a difference in the version of the Humanizer dependency between EFCore and EntityGraphQL?

Thanks!

**Comment by lukemurray** [comment]
This should be resolved in `0.68.1` which I just pushed to nuget. It contains fix #80 which fixes #70 and this issue is the same as #70 by the looks.
